// filepath: /Users/alexfedorov/Developer/GitHub/liliya-trainer-owner/netlify.toml
[build]
  publish = "/"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = false
