// filepath: /Users/alexfedorov/Developer/GitHub/liliya-trainer-owner/netlify.toml
[build]
  publish = "/"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
